# Generated by Django 5.0.6 on 2024-07-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordcompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordcompany',
            old_name='user',
            new_name='owner',
        ),
    ]
