# Generated by Django 5.0.6 on 2024-07-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_passwordcompany_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordcompany',
            old_name='company_name',
            new_name='service_name',
        ),
    ]
