version: '3'

services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: always
    env_file: .env

    volumes:
      - ./data/db/data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: django
      restart: always
      env_file: .env
      links:
        - postgres
      ports:
        - "8000:8000"
      depends_on:
        postgres:
          condition: service_healthy